<?php
require __DIR__.'/../app/domain.php';require __DIR__.'/../app/accounts.php';require __DIR__.'/../app/progress.php';require __DIR__.'/../app/store.php';
$count=0;
function check($ok,$label){global $count;if(!$ok)throw new RuntimeException($label);$count++;}
function denied($fn,$status){try{$fn();}catch(AppError $e){check($e->status===$status,'Expected '.$status.', got '.$e->status);return;}throw new RuntimeException('Expected rejection');}
$s=initial_state();$accounts=[];foreach($s['users'] as $u)$accounts[]=['id'=>$u['id'],'name'=>$u['id']==='u2'?'Anne':$u['name'],'username'=>'user'.$u['id'],'password'=>'fixture-password-123'];setup_accounts($s,['adminId'=>'u1','accounts'=>$accounts]);$admin=$s['users'][0];$parent=$s['users'][1];$kid=$s['users'][2];
check($kid['memberType']==='child'&&count($kid['routineSchedule'])===8,'Older children get daily program');check(member_snapshot($s,$kid)['dailyRoutines']!==[],'Child snapshot includes routines');check(member_snapshot($s,$parent)['canViewProgress'],'Nonadmin parent has report access');check(!member_snapshot($s,$kid)['canViewProgress'],'Child cannot view reports');
$program=[['id'=>'bed','title'=>'Yatağını topla','icon'=>'🛏️','time'=>'07:00','until'=>'12:00','points'=>10],['id'=>'teeth','title'=>'Dişlerini fırçala','icon'=>'🪥','time'=>'08:00','until'=>'12:00','points'=>10],['id'=>'night','title'=>'Pijama','icon'=>'🌙','time'=>'20:00','until'=>'23:00','points'=>10]];
$s['users'][2]['routineSchedule']=$program;$s['users'][2]['routineTrackingSince']='2026-09-28';$s['users'][2]['routineTrackingAt']='2026-09-28T00:00:00+03:00';$s['users'][2]['routineHistory']=[['day'=>'2026-09-28','schedule'=>$program]];$kid=$s['users'][2];
foreach([['2026-09-28','bed',true],['2026-09-29','bed',false],['2026-09-30','teeth',true],['2026-10-02','bed',true]] as [$day,$task,$approve]){
 $at=new DateTimeImmutable($day.'T09:00:00+03:00');complete_routine($s,$kid,['routineId'=>$task,'day'=>$day],$at);$a=end($s['assignments']);if($approve)mutate($s,'reviewAssignment',['assignmentId'=>$a['id'],'actorId'=>'u1','decision'=>'approve'],$at);
}
$now=new DateTimeImmutable('2026-10-03T10:00:00+03:00');$query=['mode'=>'week','date'=>'2026-10-03','source'=>'daily','childId'=>'u3'];$r=child_progress($s,$parent,$query,$now);
check($r['start']==='2026-09-28'&&$r['end']==='2026-10-04','Monday-Sunday week across month boundary');check($r['summary']['total']===17,'Missed days counted and future nights excluded');check($r['summary']['completed']===3&&$r['summary']['pending']===1,'Pending does not count as success');check($r['summary']['rate']===17.6,'Overall ratio weighted by occurrence count');
$tasks=array_column($r['rows'][0]['tasks'],null,'id');check($tasks['bed']['total']===6&&$tasks['bed']['rate']===33.3,'Per-task rate correct');check($tasks['teeth']['total']===6&&$tasks['teeth']['rate']===16.7,'Morning tasks with different ids separated');check($tasks['night']['total']===5,'Not-yet-due evening task excluded');check($r['days'][6]['total']===0&&$r['days'][6]['rate']===null,'Future Sunday is not zero-percent failure');
$today=child_progress($s,$parent,array_merge($query,['mode'=>'day']),$now);check($today['summary']['total']===2&&$today['summary']['active']===2,'Day view includes arrived active tasks');
$future=child_progress($s,$parent,array_merge($query,['date'=>'2026-10-05']),$now);check($future['summary']['total']===0&&$future['summary']['rate']===null,'Future week has no denominator');
$past=child_progress($s,$parent,array_merge($query,['date'=>'2026-09-20']),$now);check($past['summary']['total']===0,'No invented misses before tracking start');
$newChild=$s;$newChild['assignments']=[];$newChild['users'][2]['routineTrackingAt']='2026-10-03T18:00:00+03:00';check(child_progress($newChild,$parent,['mode'=>'day','date'=>'2026-10-03','childId'=>'u3'],new DateTimeImmutable('2026-10-03T21:00:00+03:00'))['summary']['total']===1,'First-day tasks already expired before tracking began are excluded');
$edited=$s;save_routines($edited,['id'=>'u3','routines'=>[]],new DateTimeImmutable('2026-10-05T09:00:00+03:00'));check(child_progress($edited,$parent,$query,$now)['summary']===$r['summary'],'Deleting schedule next week preserves last week');
$changed=$s;save_routines($changed,['id'=>'u3','routines'=>array_slice($program,1)],new DateTimeImmutable('2026-10-03T09:00:00+03:00'));check(child_progress($changed,$parent,['mode'=>'day','date'=>'2026-09-28','childId'=>'u3'],$now)['summary']['total']===3,'Schedule edit preserves earlier day denominator');
$legacy=$s;$legacy['users'][2]['routineHistory']=[['day'=>'2026-10-03','schedule'=>$program]];$legacy['users'][2]['routineTrackingSince']='2026-10-03';$legacy['users'][2]['routineTrackingAt']='2026-10-03T00:00:00+03:00';check(child_progress($legacy,$parent,['mode'=>'day','date'=>'2026-09-28','childId'=>'u3'],$now)['summary']['total']===1,'Pretracking submitted task remains visible without inventing missing tasks');
$at=new DateTimeImmutable('2026-10-03T09:00:00+03:00');mutate($s,'selectGoal',['userId'=>'u3','rewardId'=>$s['rewards'][array_search('u3',array_column($s['rewards'],'ownerId'))]['id']],$at);$wheel=spin($s,'u3','weekly',uid(),$at)['assignment'];
$wr=child_progress($s,$parent,array_merge($query,['source'=>'wheel']),$now);check($wr['summary']['total']===1&&$wr['summary']['active']===1,'Wheel source uses assigned-date cohort');check(child_progress($s,$parent,$query,$now)['summary']===$r['summary'],'Wheel assignments cannot inflate routine report');
mutate($s,'complete',['assignmentId'=>$wheel['id'],'userId'=>'u3','reviewerId'=>'u2'],$at);mutate($s,'reviewAssignment',['assignmentId'=>$wheel['id'],'actorId'=>'u2','decision'=>'approve'],$at);
check(child_progress($s,$parent,array_merge($query,['source'=>'wheel']),$now)['summary']['rate']===100.0,'Approved wheel task reports separately');
foreach(['2026-02-30','2026-13-01','garbage','1999-01-01'] as $bad)denied(fn()=>child_progress($s,$parent,['date'=>$bad],$now),400);
denied(fn()=>child_progress($s,$kid,$query,$now),403);denied(fn()=>child_progress($s,$parent,['mode'=>'month'],$now),400);denied(fn()=>child_progress($s,$parent,['source'=>'private'],$now),400);denied(fn()=>child_progress($s,$parent,['childId'=>'u1'],$now),404);
check(!str_contains(json_encode($r),'passwordHash')&&!str_contains(json_encode($r),'username'),'Report contains no credentials');check(!str_contains(json_encode(member_snapshot($s,$kid)),'routineHistory'),'History not leaked in normal snapshot');
$at=new DateTimeImmutable('2026-10-03T10:00:00+03:00');complete_routine($s,$kid,['routineId'=>'bed','day'=>'2026-10-03'],$at);$a=end($s['assignments']);mutate($s,'reviewAssignment',['assignmentId'=>$a['id'],'actorId'=>'u1','decision'=>'reject'],$at);
denied(function()use(&$s,$a,$at){mutate($s,'complete',['assignmentId'=>$a['id'],'userId'=>'u3','reviewerId'=>'u4'],$at);},403);
complete_routine($s,$kid,['routineId'=>'bed','day'=>'2026-10-03'],$at);mutate($s,'reviewAssignment',['assignmentId'=>$a['id'],'actorId'=>'u1','decision'=>'approve'],$at->modify('+1 day'));
check(child_progress($s,$parent,['mode'=>'day','date'=>'2026-10-03','childId'=>'u3'],$at->modify('+1 day'))['summary']['completed']===1,'Delayed approval belongs to original routine day');
$boundary=child_progress($s,$parent,['mode'=>'day','date'=>'2026-10-03','childId'=>'u3'],new DateTimeImmutable('2026-10-03T04:00:00Z'));check($boundary['summary']['total']>=1,'Exact start evaluated in Istanbul');
$store=new Store(['environment'=>'development','driver'=>'sqlite','sqlite_path'=>':memory:']);$store->initialize();$old=initial_state();$old['version']=7;foreach($old['users'] as &$u){unset($u['routineHistory'],$u['routineTrackingSince']);}unset($u);$store->db->prepare('UPDATE homedojo_state SET payload=? WHERE id=1')->execute([json_encode($old)]);$store->read();$persisted=json_decode($store->db->query('SELECT payload FROM homedojo_state WHERE id=1')->fetchColumn(),true);check($persisted['version']===8&&isset($persisted['users'][0]['routineTrackingSince']),'First read persists tracking baseline once');
echo "✓ $count child routines, parent report, historical denominator, date and access checks passed.\n";
